apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: sre-team
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "HTTPS_PROXY"
                    value: "http://192.168.216.1:7890"
                  - name: "HTTP_PROXY"
                    value: "http://192.168.216.1:7890"
                  - name: "NO_PROXY"
                    value: ".cluster.local.,.cluster.local,.svc,localhost,127.0.0.1,0.0.0.0,192.168.216.0/24,192.168.200.0/24,192.168.59.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12"      
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
